update MOM6, ocean_BGC hashes and model configs, add NWA12.CFC test, and refactor NWA12.COBALT test (#20)
* updated MOM6, ocean_BGC hashes, model configs, xmls, added NWA12.CFC CI test

* refactor CI tests

* add FMS1 build option

diff --git a/.github/workflows/mom6_cobalt_1D.yaml b/.github/workflows/mom6_cobalt_1D.yaml
--- a/.github/workflows/mom6_cobalt_1D.yaml
+++ b/.github/workflows/mom6_cobalt_1D.yaml
@@ -10,6 +10,10 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
+    container:
+      image: clouden90/1d_mom6_cobalt:base
+      options: --user=root
+        
     env:
       PR_NUMBER: ${{ github.event.number }}
 
@@ -19,37 +23,29 @@ jobs:
       with:
         submodules: recursive
         
-#    - uses: jitterbit/get-changed-files@v1
-#      id: abc
-#      with:
-#        format: space-delimited
-#        token: ${{ secrets.GITHUB_TOKEN }}        
-          
-#    - name: Login to DockerHub Registry
-#      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-          
-    - name: Build mom6_obgc 1D Docker Image
+    - name: Build mom6-sis2-cobalt
       run: |
-        echo "maximize disk space on git-runner ..."
-        df -h 
-        sudo rm -rf /usr/share/dotnet
-        sudo rm -rf /opt/ghc
-        sudo rm -rf "/usr/local/share/boost"
-        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
-        df -h
-        echo "docker image build ..."
-        docker build --file "./ci/docker/Dockerfile.ci" -t mom6_obgc_1d:develop .
+        apt update; apt install -y wget
+        echo "build mom6-sis2-cobalt ..."
+        cd ./builds
+        ./linux-build.bash -m docker -p linux-gnu -t debug -f mom6sis2
 
-    - name: Check mom6_obgc 1D Docker Image build
+    - name: Download 1d model dataset
       run: | 
-       docker images 
-       if [[ $(docker image inspect mom6_obgc_1d:develop) ]]; then
-            echo "mom6_obgc_1d:develop generated ..."          
-       else
-            echo "mom6_obgc_1d:develop was not generated ..."
-            exit 1
-       fi
+       cd ./exps
+       wget -q ftp.gfdl.noaa.gov:/pub/Yi-cheng.Teng/1d_datasets.tar.gz && tar -zxvf 1d_datasets.tar.gz && rm -rf 1d_datasets.tar.gz
 
-#    - name: Docker Logout
-#      run: |
-#       docker logout   
+    - name: Run 1D toy case and check repro across restarts
+      run: | 
+       cd exps/OM4.single_column.COBALT
+       #mpirun --allow-run-as-root -np 1 ../../builds/build/docker-linux-gnu/ocean_ice/prod/MOM6SIS2
+       ./driver.sh 
+
+    - name: Check ref
+      run: | 
+       cd exps/OM4.single_column.COBALT
+       echo "new 48hrs ocean.stats: "
+       cat ./RESTART_48hrs/ocean.stats
+       echo "baseline 48 hrs ocean.stats: "
+       cat ./ref/ocean.stats
+       diff -q ref/ocean.stats ./RESTART_48hrs/ocean.stats > /dev/null || { echo "Error: ocean.stats are different."; echo "Plz update exps/OM4.single_column.COBALT/ref/ocean.stats with the following: "; cat ./RESTART_48hrs/ocean.stats; exit 1; }
